version: 2
updates:
  # npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 5
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'npm'
    # Group related packages together
    groups:
      unit-test:
        patterns:
          - '@testing-library/*'
          - 'jest*'
          - '@types/jest'
      eslint:
        patterns:
          - '@grafana/eslint-config'
          - 'eslint*'
          - '@typescript-eslint/*'
          - '@stylistic/*'
      grafana:
        patterns:
          - '@grafana/*'
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(ci)'
    labels:
      - 'dependencies'
      - 'github-actions'

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "github.com/grafana/grafana-plugin-sdk-go"
        dependency-type: "all"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
