version: '3.0'

services:
  grafana:
    build:
      args:
        grafana_version: ${GRAFANA_VERSION:-9.5.3}
    environment:
      - GF_INSTALL_PLUGINS=snuids-trafficlights-panel
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
